name: Django CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Get code
      - uses: actions/checkout@v4

      # 2️⃣ Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt

      # 4️⃣ Run Django checks
      - name: Run Django server check
        run: python manage.py check

      # 5️⃣ Run tests
      - name: Run tests
        run: python manage.py test
